var fullItemList = [
  {id: 200, name: "Estus Flask", type: "item", amount: 0, locations: ["undeadAsylum"]},
  {id: 106, name: "Orange Guidance Soapstone", type: "item", amount: 0, locations: ['undeadBurg']},
  {id: 100, name: "White Sign Soapstone", type: "item", amount: 0, locations: ['undeadBurg']},
  {id: 375, name: "Sunlight Medal", type: "item", amount: 0, locations: ['firelinkShrine','anorLondo','demonsRuins','special']},
  {id: 101, name: "Red Sign Soapstone", type: "item", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 102, name: "Red Eye Orb", type: "item", amount: 0, locations: ['theAbyss']},
  {id: 111, name: "Cracked Red Eye Orb", type: "item", amount: 0, locations: ['firelinkShrine','newLondoRuins']},
  {id: 113, name: "Blue Eye Orb", type: "item", amount: 0, locations: ['anorLondo']},
  {id: 374, name: "Souvenir of Reprisal", type: "item", amount: 0, locations: ['anorLondo','paintedWorldOfAriamis','undeadBurg','special']},
  {id: 115, name: "Black Eye Orb", type: "item", amount: 0, locations: ['firelinkShrine']},
//  {id: 116, name: "Black Eye Orb", type: "item", amount: 0, locations: []},
  {id: 114, name: "Dragon Eye", type: "item", amount: 0, locations: ['ashLake']},
  {id: 377, name: "Dragon Head Stone", type: "item", amount: 0, locations: ['ashLake']},
  {id: 378, name: "Dragon Torso Stone", type: "item", amount: 0, locations: ['ashLake']},
  {id: 109, name: "Eye of Death", type: "item", amount: 0, locations: ['theCatacombs','tombOfTheGiants','firelinkShrine','depths','theGreatHollow','ashLake']},
  {id: 103, name: "Black Separation Crystal", type: "item", amount: 0, locations: ['special']},
  {id: 118, name: "Purple Coward's Crystal", type: "item", amount: 0, locations: ['oolacileTownship']},
  {id: 108, name: "Book of the Guilty", type: "item", amount: 0, locations: ['undeadParish']},
  {id: 373, name: "Indictment", type: "item", amount: 0, locations: ['undeadParish']},
  {id: 112, name: "Servant Roster", type: "item", amount: 0, locations: ['quelaagDomain']},
  {id: 260, name: "Green Blossom", type: "item", amount: 0, locations: ['senFortress','royalWood','darkrootGarden']},
  {id: 230, name: "Elizabeth's Mushroom", type: "item", amount: 0, locations: ['royalWood','oolacileSanctuary']},
  {id: 270, name: "Bloodred Moss Clump", type: "item", amount: 0, locations: ['undeadAsylum','darkrootGarden','royalWood']},
  {id: 271, name: "Purple Moss Clump", type: "item", amount: 0, locations: ['undeadBurg','darkrootGarden','royalWood','blighttown']},
  {id: 272, name: "Blooming Purple Moss Clump", type: "item", amount: 0, locations: ['undeadBurg','darkrootGarden','royalWood','blighttown']},
  {id: 274, name: "Purging Stone", type: "item", amount: 0, locations: ['undeadParish','undeadBurg','undeadAsylum','ashLake','crystalCave']},
  {id: 275, name: "Egg Vermifuge", type: "item", amount: 0, locations: ['blighttown','paintedWorldOfAriamis','darkrootGarden','demonsRuins']},
  {id: 240, name: "Divine Blessing", type: "item", amount: 0, locations: ['undeadParish','firelinkShrine','darkrootGarden','senFortress','lostIzalith','special']},
  {id: 292, name: "Firebomb", type: "item", amount: 0, locations: ['undeadBurg','firelinkShrine','undeadBurg']},
  {id: 297, name: "Black Firebomb", type: "item", amount: 0, locations: ['senFortress','royalWood','undeadBurg','special']},
  {id: 290, name: "Throwing Knife", type: "item", amount: 0, locations: ['undeadBurg','anorLondo']},
  {id: 291, name: "Poison Throwing Knife", type: "item", amount: 0, locations: ['undeadBurg']},
  {id: 293, name: "Dung Pie", type: "item", amount: 0, locations: ['undeadBurg','oolacileTownship','blighttown']},
  {id: 280, name: "Repair Powder", type: "item", amount: 0, locations: ['undeadBurg','royalWood']},
  {id: 310, name: "Charcoal Pine Resin", type: "item", amount: 0, locations: ['undeadBurg']},
  {id: 311, name: "Gold Pine Resin", type: "item", amount: 0, locations: ['undeadBurg','oolacileSanctuary','darkrootGarden']},
  {id: 313, name: "Rotten Pine Resin", type: "item", amount: 0, locations: ['undeadBurg']},
  {id: 296, name: "Lloyd's Talisman", type: "item", amount: 0, locations: ['undeadBurg','royalWood','firelinkShrine']},
  {id: 294, name: "Alluring Skull", type: "item", amount: 0, locations: ['undeadBurg','royalWood','undeadParish']},
  {id: 312, name: "Transient Curse", type: "item", amount: 0, locations: ['undeadBurg','newLondoRuins']},
  {id: 330, name: "Homeward Bone", type: "item", amount: 0, locations: ['undeadBurg','undeadParish','theCatacombs','oolacileTownship','royalWood','special']},
  {id: 370, name: "Prism Stone", type: "item", amount: 0, locations: ['undeadBurg','firelinkShrine','oolacileTownship','theDukeArchives']},
  {id: 510, name: "Hello Carving", type: "item", amount: 0, locations: ['oolacileTownship']},
  {id: 511, name: "Thank You Carving", type: "item", amount: 0, locations: ['oolacileTownship']},
  {id: 512, name: "Very Good! Carving", type: "item", amount: 0, locations: ['oolacileTownship']},
  {id: 513, name: "I'm Sorry Carving", type: "item", amount: 0, locations: ['oolacileTownship']},
  {id: 514, name: "Help Me! Carving", type: "item", amount: 0, locations: ['chasmOfTheAbyss']},
  {id: 371, name: "Binoculars", type: "item", amount: 0, locations: ['special', 'firelinkShrine']},
  {id: 400, name: "Soul of a Lost Undead", type: "item", amount: 0, locations: ['undeadAsylum','firelinkShrine','undeadBurg','blighttown']},
  {id: 401, name: "Large Soul of a Lost Undead", type: "item", amount: 0, locations: ['firelinkShrine','undeadBurg','undeadParish','blighttown']},
  {id: 402, name: "Soul of a Nameless Soldier", type: "item", amount: 0, locations: ['depths','newLondoRuins','blighttown']},
  {id: 403, name: "Large Soul of a Nameless Soldier", type: "item", amount: 0, locations: ['undeadParish','depths','blighttown','theGreatHollow','darkrootGarden','darkrootBasin','valleyOfDrakes','theCatacombs','newLondoRuins']},
  {id: 404, name: "Soul of a Proud Knight", type: "item", amount: 0, locations: ['blighttown','darkrootGarden','demonsRuins','valleyOfDrakes','theCatacombs','newLondoRuins']},
  {id: 405, name: "Large Soul of a Proud Knight", type: "item", amount: 0, locations: ['blighttown','newLondoRuins','demonsRuins']},
  {id: 406, name: "Soul of a Brave Warrior", type: "item", amount: 0, locations: ['darkrootGarden','newLondoRuins']},
  {id: 407, name: "Large Soul of a Brave Warrior", type: "item", amount: 0, locations: ['darkrootGarden']},
  {id: 408, name: "Soul of a Hero", type: "item", amount: 0, locations: ['anorLondo','senFortress']},
  {id: 409, name: "Soul of a Great Hero", type: "item", amount: 0, locations: ['theDukeArchives','lostIzalith']},
  {id: 390, name: "Fire Keeper Soul", type: "item", amount: 0, locations: ['anorLondo']},
  {id: 391, name: "Fire Keeper Soul", type: "item", amount: 0, locations: ['quelaagDomain']},
  {id: 392, name: "Fire Keeper Soul", type: "item", amount: 0, locations: ['firelinkShrine']},
  {id: 393, name: "Fire Keeper Soul", type: "item", amount: 0, locations: ['undeadParish']},
  {id: 394, name: "Fire Keeper Soul", type: "item", amount: 0, locations: ['newLondoRuins']},
  {id: 395, name: "Fire Keeper Soul", type: "item", amount: 0, locations: ['blighttown']},
  {id: 396, name: "Fire Keeper Soul", type: "item", amount: 0, locations: ['theDukeArchives']},
  {id: 705, name: "Soul of the Moonlight Butterfly", type: "item", amount: 0, locations: ['darkrootGarden']},
  {id: 700, name: "Soul of Quelaag", type: "item", amount: 0, locations: ['quelaagDomain']},
  {id: 703, name: "Core of an Iron Golem", type: "item", amount: 0, locations: ['senFortress']},
  {id: 704, name: "Soul of Ornstein", type: "item", amount: 0, locations: ['anorLondo']},
  {id: 706, name: "Soul of Smough", type: "item", amount: 0, locations: ['anorLondo']},
  {id: 701, name: "Soul of Sif", type: "item", amount: 0, locations: ['darkrootGarden']},
  {id: 708, name: "Soul of Gwyndolin", type: "item", amount: 0, locations: ['anorLondo']},
  {id: 707, name: "Soul of Priscilla", type: "item", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 709, name: "Guardian Soul", type: "item", amount: 0, locations: ['oolacileSanctuary']},
  {id: 710, name: "Soul of Artorias", type: "item", amount: 0, locations: ['oolacileTownship']},
  {id: 711, name: "Soul of Manus", type: "item", amount: 0, locations: ['chasmOfTheAbyss']},
  {id: 702, name: "Soul of Gwyn, Lord of Cinder", type: "item", amount: 0, locations: ['kilnOfTheFirstFlame']},
  {id: 500, name: "Humanity", type: "item", amount: 0, locations: ['firelinkShrine','depths','undeadBurg','undeadParish','valleyOfDrakes','tombOfTheGiants','crystalCave','paintedWorldOfAriamis','theDukeArchives','chasmOfTheAbyss','special']},
  {id: 501, name: "Twin Humanities", type: "item", amount: 0, locations: ['undeadBurg','lostIzalith','blighttown','darkrootGarden','chasmOfTheAbyss','special']},
  {id: 376, name: "Pendant", type: "item", amount: 0, locations: ['undeadParish','special']},
  {id: 220, name: "Silver Pendant", type: "item", amount: 0, locations: ['oolacileTownship']},
  {id: 380, name: "Rubbish", type: "item", amount: 0, locations: ['undeadBurg','oolacileTownship']},
  {id: 381, name: "Copper Coin", type: "item", amount: 0, locations: ['firelinkShrine']},
  {id: 382, name: "Silver Coin", type: "item", amount: 0, locations: ['anorLondo']},
  {id: 383, name: "Gold Coin", type: "item", amount: 0, locations: ['paintedWorldOfAriamis','royalWood','anorLondo']},
  {id: 117, name: "Darksign", type: "item", amount: 0, locations: ['special']},
  {id: 385, name: "Dried Finger", type: "item", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 1000, name: "Titanite Shard", type: "material", amount: 0, locations: ['theCatacombs','undeadParish','senFortress','undeadBurg','undeadAsylum','special']},
  {id: 1010, name: "Large Titanite Shard", type: "material", amount: 0, locations: ['senFortress','anorLondo','oolacileTownship','paintedWorldOfAriamis','blighttown','depths','theGreatHollow','darkrootBasin']},
  {id: 1030, name: "Titanite Chunk", type: "material", amount: 0, locations: ['anorLondo','newLondoRuins','undeadAsylum','undeadParish','undeadBurg','kilnOfTheFirstFlame']},
  {id: 1070, name: "Titanite Slab", type: "material", amount: 0, locations: ['ashLake','royalWood','undeadAsylum','newLondoRuins','theGreatHollow']},
  {id: 1020, name: "Green Titanite Shard", type: "material", amount: 0, locations: ['senFortress','anorLondo','oolacileTownship','depths','blighttown','demonsRuins','theCatacombs','newLondoRuins']},
  {id: 1040, name: "Blue Titanite Chunk", type: "material", amount: 0, locations: ['darkrootBasin','kilnOfTheFirstFlame','crystalCave','theDukeArchives','theGreatHollow','special']},
  {id: 1080, name: "Blue Titanite Slab", type: "material", amount: 0, locations: ['crystalCave','royalWood']},
  {id: 1060, name: "Red Titanite Chunk", type: "material", amount: 0, locations: ['demonsRuins','lostIzalith','kilnOfTheFirstFlame','undeadAsylum']},
  {id: 1100, name: "Red Titanite Slab", type: "material", amount: 0, locations: ['lostIzalith','undeadAsylum']},
  {id: 1050, name: "White Titanite Chunk", type: "material", amount: 0, locations: ['tombOfTheGiants','undeadAsylum','kilnOfTheFirstFlame']},
  {id: 1090, name: "White Titanite Slab", type: "material", amount: 0, locations: ['chasmOfTheAbyss','tombOfTheGiants']},
  {id: 1130, name: "Twinkling Titanite", type: "material", amount: 0, locations: ['anorLondo','royalWood','theDukeArchives','ashLake','undeadAsylum','darkrootBasin','theCatacombs','crystalCave','lostIzalith','theGreatHollow']},
  {id: 1120, name: "Demon Titanite", type: "material", amount: 0, locations: ['undeadAsylum','anorLondo','undeadParish','theCatacombs','senFortress','lostIzalith']},
  {id: 1110, name: "Dragon Scale", type: "material", amount: 0, locations: ['darkrootBasin','ashLake','paintedWorldOfAriamis','valleyOfDrakes','undeadAsylum','blighttown']},
  {id: 2510, name: "Lordvessel", type: "key_item", amount: 0, locations: ['anorLondo']},
  {id: 2500, name: "Lord Soul", type: "key_item", amount: 0, locations: ['tombOfTheGiants']},
  {id: 2501, name: "Lord Soul", type: "key_item", amount: 0, locations: ['lostIzalith']},
  {id: 2502, name: "Bequeathed Lord Soul Shard", type: "key_item", amount: 0, locations: ['theAbyss']},
  {id: 2503, name: "Bequeathed Lord Soul Shard", type: "key_item", amount: 0, locations: ['crystalCave']},
  {id: 800, name: "Large Ember", type: "key_item", amount: 0, locations: ['depths']},
  {id: 801, name: "Very Large Ember", type: "key_item", amount: 0, locations: ['newLondoRuins']},
  {id: 802, name: "Crystal Ember", type: "key_item", amount: 0, locations: ['theDukeArchives']},
  {id: 812, name: "Large Flame Ember", type: "key_item", amount: 0, locations: ['demonsRuins']},
  {id: 813, name: "Chaos Flame Ember", type: "key_item", amount: 0, locations: ['demonsRuins']},
  {id: 806, name: "Large Magic Ember", type: "key_item", amount: 0, locations: ['theDukeArchives']},
  {id: 807, name: "Enchanted Ember", type: "key_item", amount: 0, locations: ['darkrootGarden']},
  {id: 808, name: "Divine Ember", type: "key_item", amount: 0, locations: ['darkrootGarden']},
  {id: 809, name: "Large Divine Ember", type: "key_item", amount: 0, locations: ['tombOfTheGiants']},
  {id: 810, name: "Dark Ember", type: "key_item", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 2602, name: "Repairbox", type: "key_item", amount: 0, locations: ['undeadBurg','undeadParish']},
  {id: 2600, name: "Weapon Smithbox", type: "key_item", amount: 0, locations: ['undeadParish']},
  {id: 2601, name: "Armor Smithbox", type: "key_item", amount: 0, locations: ['undeadParish']},
  {id: 2608, name: "Bottomless Box", type: "key_item", amount: 0, locations: ['firelinkShrine','undeadBurg']},
  {id: 2607, name: "Rite of Kindling", type: "key_item", amount: 0, locations: ['theCatacombs']},
  {id: 384, name: "Peculiar Doll", type: "key_item", amount: 0, locations: ['undeadAsylum']},
  {id: 2520, name: "Broken Pendant", type: "key_item", amount: 0, locations: ['theDukeArchives']},
  {id: 2100, name: "Master Key", type: "key_item", amount: 0, locations: ['special','firelinkShrine']},
  {id: 2002, name: "Crest of Artorias", type: "key_item", amount: 0, locations: ['undeadParish']},
  {id: 2010, name: "Dungeon Cell Key", type: "key_item", amount: 0, locations: ['undeadAsylum']},
  {id: 2012, name: "Undead Asylum F2 East Key", type: "key_item", amount: 0, locations: ['undeadAsylum']},
  {id: 2016, name: "Undead Asylum F2 West Key", type: "key_item", amount: 0, locations: ['firelinkShrine']},
  {id: 2011, name: "Big Pilgrim's Key", type: "key_item", amount: 0, locations: ['undeadAsylum']},
  {id: 2021, name: "Residence Key", type: "key_item", amount: 0, locations: ['undeadBurg']},
  {id: 2017, name: "Mystery Key", type: "key_item", amount: 0, locations: ['undeadParish']},
  {id: 2001, name: "Basement Key", type: "key_item", amount: 0, locations: ['undeadParish']},
  {id: 2014, name: "Key to Depths", type: "key_item", amount: 0, locations: ['undeadBurg']},
  {id: 2019, name: "Watchtower Basement Key", type: "key_item", amount: 0, locations: ['darkrootGarden']},
  {id: 2018, name: "Sewer Chamber Key", type: "key_item", amount: 0, locations: ['depths']},
  {id: 2007, name: "Blighttown Key", type: "key_item", amount: 0, locations: ['depths']},
  {id: 2008, name: "Key to New Londo Ruins", type: "key_item", amount: 0, locations: ['blighttown']},
  {id: 2013, name: "Key to the Seal", type: "key_item", amount: 0, locations: ['newLondoRuins']},
  {id: 2003, name: "Cage Key", type: "key_item", amount: 0, locations: ['senFortress']},
  {id: 2004, name: "Archive Tower Cell Key", type: "key_item", amount: 0, locations: ['theDukeArchives']},
  {id: 2020, name: "Archive Prison Extra Key", type: "key_item", amount: 0, locations: ['theDukeArchives']},
  {id: 2006, name: "Archive Tower Giant Cell Key", type: "key_item", amount: 0, locations: ['theDukeArchives']},
  {id: 2005, name: "Archive Tower Giant Door Key", type: "key_item", amount: 0, locations: ['theDukeArchives']},
  {id: 2009, name: "Annex Key", type: "key_item", amount: 0, locations: ['paintedWorldOfAriamis']},
  //  {id: 2015, name: "Lift Chamber Key", type: "key_item", amount: 0, locations: []},
  {id: 2022, name: "Crest Key", type: "key_item", amount: 0, locations: ['oolacileTownship']},
  {id: 3000, name: "Sorcery: Soul Arrow", type: "magic", amount: 0, locations: ['newLondoRuins','firelinkShrine','theDukeArchives','special']},
  {id: 3010, name: "Sorcery: Great Soul Arrow", type: "magic", amount: 0, locations: ['firelinkShrine','theDukeArchives']},
  {id: 3020, name: "Sorcery: Heavy Soul Arrow", type: "magic", amount: 0, locations: ['newLondoRuins','firelinkShrine','theDukeArchives']},
  {id: 3030, name: "Sorcery: Great Heavy Soul Arrow", type: "magic", amount: 0, locations: ['firelinkShrine','theDukeArchives']},
  {id: 3040, name: "Sorcery: Homing Soulmass", type: "magic", amount: 0, locations: ['firelinkShrine','theDukeArchives']},
  {id: 3050, name: "Sorcery: Homing Crystal Soulmass", type: "magic", amount: 0, locations: ['theDukeArchives']},
  {id: 3060, name: "Sorcery: Soul Spear", type: "magic", amount: 0, locations: ['firelinkShrine','theDukeArchives']},
  {id: 3070, name: "Sorcery: Crystal Soul Spear", type: "magic", amount: 0, locations: ['theDukeArchives']},
  {id: 3700, name: "Sorcery: White Dragon Breath", type: "magic", amount: 0, locations: ['theDukeArchives']},
  {id: 3100, name: "Sorcery: Magic Weapon", type: "magic", amount: 0, locations: ['firelinkShrine','theDukeArchives']},
  {id: 3110, name: "Sorcery: Great Magic Weapon", type: "magic", amount: 0, locations: ['anorLondo']},
  {id: 3120, name: "Sorcery: Crystal Magic Weapon", type: "magic", amount: 0, locations: ['theDukeArchives']},
  {id: 3300, name: "Sorcery: Magic Shield", type: "magic", amount: 0, locations: ['firelinkShrine','theDukeArchives']},
  {id: 3310, name: "Sorcery: Strong Magic Shield", type: "magic", amount: 0, locations: ['theDukeArchives']},
  {id: 3520, name: "Sorcery: Aural Decoy", type: "magic", amount: 0, locations: ['firelinkShrine']},
  {id: 3510, name: "Sorcery: Hush", type: "magic", amount: 0, locations: ['firelinkShrine','senFortress']},
  {id: 3540, name: "Sorcery: Fall Control", type: "magic", amount: 0, locations: ['firelinkShrine']},
  {id: 3400, name: "Sorcery: Hidden Weapon", type: "magic", amount: 0, locations: ['oolacileSanctuary','darkrootBasin']},
  {id: 3410, name: "Sorcery: Hidden Body", type: "magic", amount: 0, locations: ['oolacileSanctuary','darkrootBasin']},
  {id: 3530, name: "Sorcery: Repair", type: "magic", amount: 0, locations: ['oolacileSanctuary','darkrootBasin']},
  {id: 3500, name: "Sorcery: Cast Light", type: "magic", amount: 0, locations: ['oolacileSanctuary','darkrootBasin']},
  {id: 3550, name: "Sorcery: Chameleon", type: "magic", amount: 0, locations: ['oolacileSanctuary','darkrootBasin']},
  {id: 3610, name: "Sorcery: Remedy", type: "magic", amount: 0, locations: ['blighttown']},
  {id: 3600, name: "Sorcery: Resist Curse", type: "magic", amount: 0, locations: ['newLondoRuins']},
  {id: 3710, name: "Sorcery: Dark Orb", type: "magic", amount: 0, locations: ['oolacileTownship']},
  {id: 3720, name: "Sorcery: Dark Bead", type: "magic", amount: 0, locations: ['chasmOfTheAbyss']},
  {id: 3730, name: "Sorcery: Dark Fog", type: "magic", amount: 0, locations: ['oolacileTownship']},
  {id: 3740, name: "Sorcery: Pursuers", type: "magic", amount: 0, locations: ['undeadBurg']},
  {id: 4000, name: "Pyromancy: Fireball", type: "magic", amount: 0, locations: ['firelinkShrine','blighttown','special']},
  {id: 4010, name: "Pyromancy: Fire Orb", type: "magic", amount: 0, locations: ['firelinkShrine','blighttown']},
  {id: 4020, name: "Pyromancy: Great Fireball", type: "magic", amount: 0, locations: ['blighttown']},
  {id: 4500, name: "Pyromancy: Great Chaos Fireball", type: "magic", amount: 0, locations: ['quelaagDomain']},
  {id: 4030, name: "Pyromancy: Firestorm", type: "magic", amount: 0, locations: ['blighttown']},
  {id: 4040, name: "Pyromancy: Fire Tempest", type: "magic", amount: 0, locations: ['blighttown']},
  {id: 4510, name: "Pyromancy: Chaos Storm", type: "magic", amount: 0, locations: ['quelaagDomain']},
  {id: 4100, name: "Pyromancy: Combustion", type: "magic", amount: 0, locations: ['firelinkShrine','blighttown']},
  {id: 4110, name: "Pyromancy: Great Combustion", type: "magic", amount: 0, locations: ['blighttown']},
  {id: 4050, name: "Pyromancy: Fire Surge", type: "magic", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 4060, name: "Pyromancy: Fire Whip", type: "magic", amount: 0, locations: ['blighttown']},
  {id: 4520, name: "Pyromancy: Chaos Fire Whip", type: "magic", amount: 0, locations: ['lostIzalith']},
  {id: 4200, name: "Pyromancy: Poison Mist", type: "magic", amount: 0, locations: ['quelaagDomain','blighttown']},
  {id: 4210, name: "Pyromancy: Toxic Mist", type: "magic", amount: 0, locations: ['quelaagDomain']},
  {id: 4220, name: "Pyromancy: Acid Surge", type: "magic", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 4310, name: "Pyromancy: Flash Sweat", type: "magic", amount: 0, locations: ['firelinkShrine']},
  {id: 4300, name: "Pyromancy: Iron Flesh", type: "magic", amount: 0, locations: ['firelinkShrine']},
  {id: 4400, name: "Pyromancy: Power Within", type: "magic", amount: 0, locations: ['blighttown']},
  {id: 4360, name: "Pyromancy: Undead Rapport", type: "magic", amount: 0, locations: ['blighttown']},
  {id: 4530, name: "Pyromancy: Black Flame", type: "magic", amount: 0, locations: ['chasmOfTheAbyss']},
  {id: 5000, name: "Miracle: Heal", type: "magic", amount: 0, locations: ['firelinkShrine','undeadParish','special']},
  {id: 5020, name: "Miracle: Great Heal Excerpt", type: "magic", amount: 0, locations: ['firelinkShrine','undeadParish']},
  {id: 5010, name: "Miracle: Great Heal", type: "magic", amount: 0, locations: ['undeadParish']},
  {id: 5030, name: "Miracle: Soothing Sunlight", type: "magic", amount: 0, locations: ['theDukeArchives']},
  {id: 5040, name: "Miracle: Replenishment", type: "magic", amount: 0, locations: ['tombOfTheGiants']},
  {id: 5050, name: "Miracle: Bountiful Sunlight", type: "magic", amount: 0, locations: ['theDukeArchives']},
  {id: 5300, name: "Miracle: Force", type: "magic", amount: 0, locations: ['firelinkShrine','undeadParish']},
  {id: 5310, name: "Miracle: Wrath of the Gods", type: "magic", amount: 0, locations: ['undeadParish']},
  {id: 5320, name: "Miracle: Emit Force", type: "magic", amount: 0, locations: ['firelinkShrine']},
  {id: 5600, name: "Miracle: Magic Barrier", type: "magic", amount: 0, locations: ['undeadParish']},
  {id: 5610, name: "Miracle: Great Magic Barrier", type: "magic", amount: 0, locations: ['ashLake']},
  {id: 5210, name: "Miracle: Homeward", type: "magic", amount: 0, locations: ['firelinkShrine','undeadParish']},
  //  {id: 5200, name: "Miracle: Escape Death", type: "magic", amount: 0, locations: []},
  {id: 5400, name: "Miracle: Seek Guidance", type: "magic", amount: 0, locations: ['firelinkShrine','undeadParish']},
  {id: 5700, name: "Miracle: Karmic Justice", type: "magic", amount: 0, locations: ['undeadParish']},
  {id: 5810, name: "Miracle: Vow of Silence", type: "magic", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 5800, name: "Miracle: Tranquil Walk of Peace", type: "magic", amount: 0, locations: ['theCatacombs']},
  {id: 5500, name: "Miracle: Lightning Spear", type: "magic", amount: 0, locations: ['undeadParish']},
  {id: 5510, name: "Miracle: Great Lightning Spear", type: "magic", amount: 0, locations: ['undeadParish']},
  {id: 5520, name: "Miracle: Sunlight Spear", type: "magic", amount: 0, locations: ['undeadParish']},
  {id: 5900, name: "Miracle: Sunlight Blade", type: "magic", amount: 0, locations: ['anorLondo']},
  {id: 5910, name: "Miracle: Darkmoon Blade", type: "magic", amount: 0, locations: ['anorLondo']},
  {id: 5100, name: "Miracle: Gravelord Sword Dance", type: "magic", amount: 0, locations: ['tombOfTheGiants']},
  {id: 5110, name: "Miracle: Gravelord Greatsword Dance", type: "magic", amount: 0, locations: ['tombOfTheGiants']},
  {id: 100000, name: "Dagger", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 101000, name: "Parrying Dagger", type: "weapon", amount: 0, locations: ['newLondoRuins']},
  {id: 103000, name: "Bandit's Knife", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 102000, name: "Ghost Blade", type: "weapon", amount: 0, locations: ['newLondoRuins']},
  {id: 9011000, name: "Dark Silver Tracer", type: "weapon", amount: 0, locations: ['oolacileTownship']},
  {id: 104000, name: "Priscilla's Dagger", type: "weapon", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 200000, name: "Shortsword", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 201000, name: "Longsword", type: "weapon", amount: 0, locations: ['undeadAsylum','undeadBurg','undeadParish','special']},
  {id: 202000, name: "Broadsword", type: "weapon", amount: 0, locations: ['undeadParish','special']},
  {id: 204000, name: "Balder Side Sword", type: "weapon", amount: 0, locations: ['undeadParish','senFortress']},
  {id: 206000, name: "Sunlight Straight Sword", type: "weapon", amount: 0, locations: ['undeadParish','anorLondo','lostIzalith']},
  {id: 210000, name: "Darksword", type: "weapon", amount: 0, locations: ['theAbyss']},
  {id: 207000, name: "Barbed Straight Sword", type: "weapon", amount: 0, locations: ['depths','demonsRuins','lostIzalith']},
  {id: 205000, name: "Crystal Straight Sword", type: "weapon", amount: 0, locations: ['firelinkShrine','theDukeArchives']},
  {id: 208000, name: "Silv. Knight Str. Sword", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 209000, name: "Astora's Straight Sword", type: "weapon", amount: 0, locations: ['valleyOfDrakes']},
  {id: 211000, name: "Drake Sword", type: "weapon", amount: 0, locations: ['undeadParish']},
  {id: 203000, name: "Broken Straight Sword", type: "weapon", amount: 0, locations: ['undeadAsylum','paintedWorldOfAriamis','blighttown']},
  {id: 212000, name: "Straight Sword Hilt", type: "weapon", amount: 0, locations: ['special']},
  {id: 300000, name: "Bastard Sword", type: "weapon", amount: 0, locations: ['undeadParish']},
  {id: 301000, name: "Claymore", type: "weapon", amount: 0, locations: ['undeadBurg']},
  {id: 302000, name: "Man-serpent Greatsword", type: "weapon", amount: 0, locations: ['senFortress']},
  {id: 303000, name: "Flamberge", type: "weapon", amount: 0, locations: ['senFortress','blighttown']},
  {id: 304000, name: "Crystal Greatsword", type: "weapon", amount: 0, locations: ['firelinkShrine']},
  {id: 310000, name: "Black Knight Sword", type: "weapon", amount: 0, locations: ['undeadBurg','kilnOfTheFirstFlame','undeadAsylum']},
  {id: 306000, name: "Stone Greatsword", type: "weapon", amount: 0, locations: ['blighttown','darkrootGarden']},
  {id: 311000, name: "Greatsword of Artorias", type: "weapon", amount: 0, locations: ['special']},
  {id: 307000, name: "Greatsword of Artorias", type: "weapon", amount: 0, locations: ['special']},
  {id: 9012000, name: "Abyss Greatsword", type: "weapon", amount: 0, locations: ['special']},
  {id: 314000, name: "Great Lord Greatsword", type: "weapon", amount: 0, locations: ['special']},
  {id: 309000, name: "Moonlight Greatsword", type: "weapon", amount: 0, locations: ['special']},
  {id: 9020000, name: "Obsidian Greatsword", type: "weapon", amount: 0, locations: ['royalWood']},
  {id: 351000, name: "Greatsword", type: "weapon", amount: 0, locations: ['anorLondo','senFortress','paintedWorldOfAriamis','undeadParish']},
  {id: 350000, name: "Zweihander", type: "weapon", amount: 0, locations: ['firelinkShrine']},
  {id: 352000, name: "Demon Great Machete", type: "weapon", amount: 0, locations: ['undeadBurg','demonsRuins','blighttown']},
  {id: 355000, name: "Black Knight Greatsword", type: "weapon", amount: 0, locations: ['undeadParish','kilnOfTheFirstFlame']},
  {id: 354000, name: "Dragon Greatsword", type: "weapon", amount: 0, locations: ['ashLake']},
  {id: 400000, name: "Scimitar", type: "weapon", amount: 0, locations: ['undeadBurg','theCatacombs','special']},
  {id: 401000, name: "Falchion", type: "weapon", amount: 0, locations: ['blighttown','theCatacombs']},
  {id: 402000, name: "Shotel", type: "weapon", amount: 0, locations: ['senFortress','blighttown']},
  {id: 405000, name: "Painting Guardian Sword", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 403000, name: "Jagged Ghost Blade", type: "weapon", amount: 0, locations: ['newLondoRuins']},
  {id: 9010000, name: "Gold Tracer", type: "weapon", amount: 0, locations: ['oolacileTownship']},
  {id: 406000, name: "Quelaag's Furysword", type: "weapon", amount: 0, locations: ['special']},
  {id: 451000, name: "Murakumo", type: "weapon", amount: 0, locations: ['blighttown','darkrootGarden','tombOfTheGiants']},
  {id: 450000, name: "Server", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 453000, name: "Gravelord Sword", type: "weapon", amount: 0, locations: ['tombOfTheGiants']},
  {id: 500000, name: "Uchigatana", type: "weapon", amount: 0, locations: ['undeadBurg','darkrootGarden','blighttown']},
  {id: 502000, name: "Iaito", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 501000, name: "Washing Pole", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 503000, name: "Chaos Blade", type: "weapon", amount: 0, locations: ['special']},
  {id: 600000, name: "Mail Breaker", type: "weapon", amount: 0, locations: ['undeadBurg']},
  {id: 601000, name: "Rapier", type: "weapon", amount: 0, locations: ['undeadBurg','undeadParish','senFortress']},
  {id: 602000, name: "Estoc", type: "weapon", amount: 0, locations: ['newLondoRuins']},
  {id: 604000, name: "Ricard's Rapier", type: "weapon", amount: 0, locations: ['senFortress']},
  {id: 603000, name: "Velka's Rapier", type: "weapon", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 700000, name: "Hand Axe", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 701000, name: "Battle Axe", type: "weapon", amount: 0, locations: ['undeadParish','undeadBurg','special']},
  {id: 703000, name: "Butcher Knife", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 705000, name: "Gargoyle Tail Axe", type: "weapon", amount: 0, locations: ['undeadParish','anorLondo']},
  {id: 702000, name: "Crescent Axe", type: "weapon", amount: 0, locations: ['theCatacombs','tombOfTheGiants','firelinkShrine']},
  {id: 704000, name: "Golem Axe", type: "weapon", amount: 0, locations: ['special']},
  {id: 750000, name: "Greataxe", type: "weapon", amount: 0, locations: ['depths','senFortress','paintedWorldOfAriamis','undeadParish']},
  {id: 751000, name: "Demon's Greataxe", type: "weapon", amount: 0, locations: ['blighttown','undeadBurg','demonsRuins']},
  {id: 9015000, name: "Stone Greataxe", type: "weapon", amount: 0, locations: ['royalWood']},
  {id: 753000, name: "Black Knight Greataxe", type: "weapon", amount: 0, locations: ['kilnOfTheFirstFlame']},
  {id: 752000, name: "Dragon King Greataxe", type: "weapon", amount: 0, locations: ['depths']},
  {id: 800000, name: "Club", type: "weapon", amount: 0, locations: ['special','undeadBurg']},
  {id: 809000, name: "Reinforced Club", type: "weapon", amount: 0, locations: ['undeadBurg']},
  {id: 811000, name: "Blacksmith Giant Hammer", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 801000, name: "Mace", type: "weapon", amount: 0, locations: ['firelinkShrine','theCatacombs','special']},
  {id: 802000, name: "Morning Star", type: "weapon", amount: 0, locations: ['firelinkShrine']},
  {id: 803000, name: "Warpick", type: "weapon", amount: 0, locations: ['undeadParish']},
  {id: 804000, name: "Pickaxe", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 810000, name: "Blacksmith Hammer", type: "weapon", amount: 0, locations: ['undeadParish']},
  {id: 812000, name: "Hammer of Vamos", type: "weapon", amount: 0, locations: ['theCatacombs']},
  {id: 855000, name: "Large Club", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 850000, name: "Great Club", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 852000, name: "Demon's Great Hammer", type: "weapon", amount: 0, locations: ['undeadAsylum']},
  {id: 851000, name: "Grant", type: "weapon", amount: 0, locations: ['tombOfTheGiants']},
  {id: 854000, name: "Dragon Tooth", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 856000, name: "Smough's Hammer", type: "weapon", amount: 0, locations: ['special']},
  {id: 1000000, name: "Spear", type: "weapon", amount: 0, locations: ['undeadBurg','undeadParish','paintedWorldOfAriamis']},
  {id: 1001000, name: "Winged Spear", type: "weapon", amount: 0, locations: ['firelinkShrine']},
  {id: 1002000, name: "Partizan", type: "weapon", amount: 0, locations: ['darkrootGarden']},
  {id: 9016000, name: "Four-Pronged Prow", type: "weapon", amount: 0, locations: ['royalWood']},
  {id: 1050000, name: "Pike", type: "weapon", amount: 0, locations: ['undeadParish']},
  {id: 1004000, name: "Channeler's Trident", type: "weapon", amount: 0, locations: ['undeadParish','depths','theDukeArchives']},
  {id: 1003000, name: "Demon's Spear", type: "weapon", amount: 0, locations: ['anorLondo','blighttown']},
  {id: 1006000, name: "Silver Knight Spear", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 1052000, name: "Moonlight Butterfly Horn", type: "weapon", amount: 0, locations: ['special']},
  {id: 1051000, name: "Dragonslayer Spear", type: "weapon", amount: 0, locations: ['special']},
  {id: 1100000, name: "Halberd", type: "weapon", amount: 0, locations: ['undeadParish']},
  {id: 1106000, name: "Lucerne ", type: "weapon", amount: 0, locations: ['theCatacombs']},
  {id: 1107000, name: "Scythe", type: "weapon", amount: 0, locations: ['senFortress']},
  {id: 1103000, name: "Gargoyle's Halberd", type: "weapon", amount: 0, locations: ['undeadParish','anorLondo']},
  {id: 1101000, name: "Giant's Halberd", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 1102000, name: "Titanite Catch Pole", type: "weapon", amount: 0, locations: ['undeadParish','anorLondo','senFortress','theCatacombs','lostIzalith']},
  {id: 1105000, name: "Black Knight Halberd", type: "weapon", amount: 0, locations: ['darkrootBasin','kilnOfTheFirstFlame']},
  {id: 1150000, name: "Great Scythe", type: "weapon", amount: 0, locations: ['theCatacombs']},
  {id: 1151000, name: "Lifehunt Scythe", type: "weapon", amount: 0, locations: ['special']},
  {id: 1600000, name: "Whip", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 1601000, name: "Notched Whip", type: "weapon", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 9019000, name: "Guardian Tail", type: "weapon", amount: 0, locations: ['oolacileSanctuary']},
//  {id: 900000, name: "Fists", type: "weapon", amount: 0, locations: []},
  {id: 901000, name: "Caestus", type: "weapon", amount: 0, locations: ['undeadParish']},
  {id: 902000, name: "Claw", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 903000, name: "Dragon Bone Fist", type: "weapon", amount: 0, locations: ['special']},
  {id: 904000, name: "Dark Hand", type: "weapon", amount: 0, locations: ['theAbyss','newLondoRuins']},
  {id: 1200000, name: "Short Bow", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 1204000, name: "Composite Bow", type: "weapon", amount: 0, locations: ['newLondoRuins']},
  {id: 1201000, name: "Longbow", type: "weapon", amount: 0, locations: ['darkrootBasin','tombOfTheGiants','theDukeArchives']},
  {id: 1202000, name: "Black Bow of Pharis", type: "weapon", amount: 0, locations: ['darkrootGarden']},
  {id: 1203000, name: "Dragonslayer Greatbow", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 9021000, name: "Gough's Great Bow", type: "weapon", amount: 0, locations: ['oolacileTownship']},
  {id: 1205000, name: "Darkmoon Bow", type: "weapon", amount: 0, locations: ['special']},
  {id: 1250000, name: "Light Crossbow", type: "weapon", amount: 0, locations: ['undeadBurg','senFortress','undeadParish','undeadBurg']},
  {id: 1251000, name: "Heavy Crossbow", type: "weapon", amount: 0, locations: ['depths']},
  {id: 1253000, name: "Sniper Crossbow", type: "weapon", amount: 0, locations: ['senFortress']},
  {id: 1252000, name: "Avelyn", type: "weapon", amount: 0, locations: ['theDukeArchives']},
  {id: 1300000, name: "Sorcerer's Catalyst", type: "weapon", amount: 0, locations: ['firelinkShrine','newLondoRuins','undeadBurg','special']},
  {id: 1301000, name: "Beatrice's Catalyst", type: "weapon", amount: 0, locations: ['valleyOfDrakes']},
  {id: 1303000, name: "Logan's Catalyst", type: "weapon", amount: 0, locations: ['theDukeArchives']},
  {id: 1305000, name: "Oolacile Ivory Catalyst", type: "weapon", amount: 0, locations: ['darkrootBasin','oolacileSanctuary']},
  {id: 9018000, name: "Oolacile Catalyst", type: "weapon", amount: 0, locations: ['oolacileTownship']},
  {id: 1307000, name: "Demon's Catalyst", type: "weapon", amount: 0, locations: ['demonsRuins']},
  {id: 1308000, name: "Izalith Catalyst", type: "weapon", amount: 0, locations: ['lostIzalith']},
  {id: 1302000, name: "Tin Banishment Catalyst", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 1306000, name: "Tin Crystallization Ctlyst.", type: "weapon", amount: 0, locations: ['theDukeArchives']},
  {id: 1304000, name: "Tin Darkmoon Catalyst", type: "weapon", amount: 0, locations: ['special']},
  {id: 9017000, name: "Manus Catalyst", type: "weapon", amount: 0, locations: ['special']},
  {id: 1330000, name: "Pyromancy Flame", type: "weapon", amount: 0, locations: ['firelinkShrine','blighttown','special']},
  {id: 1332000, name: "Pyromancy Flame", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 1360000, name: "Talisman", type: "weapon", amount: 0, locations: ['firelinkShrine','undeadParish']},
  {id: 1361000, name: "Canvas Talisman", type: "weapon", amount: 0, locations: ['firelinkShrine','special']},
  {id: 1362000, name: "Thorolund Talisman", type: "weapon", amount: 0, locations: ['firelinkShrine']},
  {id: 1363000, name: "Ivory Talisman", type: "weapon", amount: 0, locations: ['firelinkShrine','undeadParish','theDukeArchives']},
  {id: 1365000, name: "Sunlight Talisman", type: "weapon", amount: 0, locations: ['undeadParish','anorLondo','lostIzalith']},
  {id: 1366000, name: "Darkmoon Talisman", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 1367000, name: "Velka's Talisman", type: "weapon", amount: 0, locations: ['undeadParish']},
  {id: 1396000, name: "Skull Lantern", type: "weapon", amount: 0, locations: ['theCatacombs','tombOfTheGiants']},
  {id: 1460000, name: "Warrior's Round Shield", type: "weapon", amount: 0, locations: ['undeadBurg']},
  {id: 1410000, name: "Caduceus Round Shield", type: "weapon", amount: 0, locations: ['firelinkShrine']},
  {id: 9000000, name: "Effigy Shield", type: "weapon", amount: 0, locations: ['tombOfTheGiants']},
  {id: 1476000, name: "Red and White Round Shield", type: "weapon", amount: 0, locations: ['firelinkShrine','theCatacombs']},
  {id: 1406000, name: "Cracked Round Shield", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 1409000, name: "Plank Shield", type: "weapon", amount: 0, locations: ['blighttown','special']},
  {id: 1403000, name: "Small Leather Shield", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 1408000, name: "Leather Shield", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 1405000, name: "Buckler", type: "weapon", amount: 0, locations: ['undeadBurg','undeadParish','senFortress']},
  {id: 1404000, name: "Target Shield", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 1411000, name: "Crystal Ring Shield", type: "weapon", amount: 0, locations: ['special']},
  {id: 1400000, name: "East-West Shield", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 1401000, name: "Wooden Shield", type: "weapon", amount: 0, locations: ['undeadBurg']},
  {id: 1402000, name: "Large Leather Shield", type: "weapon", amount: 0, locations: ['undeadParish','paintedWorldOfAriamis','special']},
  {id: 1450000, name: "Heater Shield", type: "weapon", amount: 0, locations: ['undeadBurg','special']},
  {id: 1452000, name: "Tower Kite Shield", type: "weapon", amount: 0, locations: ['undeadParish','special']},
  {id: 1477000, name: "Caduceus Kite Shield", type: "weapon", amount: 0, locations: ['undeadParish','theDukeArchives']},
  {id: 1454000, name: "Hollow Soldier Shield", type: "weapon", amount: 0, locations: ['undeadBurg','undeadParish']},
  {id: 1451000, name: "Knight Shield", type: "weapon", amount: 0, locations: ['undeadParish']},
  {id: 9001000, name: "Sanctus", type: "weapon", amount: 0, locations: ['tombOfTheGiants']},
  {id: 1455000, name: "Balder Shield", type: "weapon", amount: 0, locations: ['senFortress','undeadParish','senFortress']},
  {id: 1462000, name: "Spider Shield", type: "weapon", amount: 0, locations: ['depths','valleyOfDrakes','special']},
  {id: 1453000, name: "Grass Crest Shield", type: "weapon", amount: 0, locations: ['darkrootBasin']},
  {id: 9002000, name: "Bloodshield", type: "weapon", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 1461000, name: "Iron Round Shield", type: "weapon", amount: 0, locations: ['darkrootGarden','blighttown']},
  {id: 1472000, name: "Sunlight Shield", type: "weapon", amount: 0, locations: ['undeadParish','anorLondo','lostIzalith']},
  {id: 1475000, name: "Pierce Shield", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 1470000, name: "Spiked Shield", type: "weapon", amount: 0, locations: ['depths','demonsRuins','lostIzalith']},
  {id: 1478000, name: "Gargoyle's Shield", type: "weapon", amount: 0, locations: ['undeadParish','anorLondo']},
  {id: 1471000, name: "Crystal Shield", type: "weapon", amount: 0, locations: ['firelinkShrine']},
  {id: 1456000, name: "Crest Shield", type: "weapon", amount: 0, locations: ['undeadAsylum']},
  {id: 1457000, name: "Dragon Crest Shield", type: "weapon", amount: 0, locations: ['valleyOfDrakes']},
  {id: 1473000, name: "Silver Knight Shield", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 1474000, name: "Black Knight Shield", type: "weapon", amount: 0, locations: ['undeadAsylum','undeadBurg','undeadParish','darkrootBasin','tombOfTheGiants','kilnOfTheFirstFlame']},
  {id: 1500000, name: "Eagle Shield", type: "weapon", amount: 0, locations: ['blighttown']},
  {id: 1501000, name: "Tower Shield", type: "weapon", amount: 0, locations: ['senFortress','undeadParish','senFortress','paintedWorldOfAriamis']},
  {id: 9003000, name: "Black Iron Greatshield", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 1502000, name: "Giant Shield", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 1506000, name: "Bonewheel Shield", type: "weapon", amount: 0, locations: ['theCatacombs','paintedWorldOfAriamis']},
  {id: 1503000, name: "Stone Greatshield", type: "weapon", amount: 0, locations: ['darkrootGarden']},
  {id: 1505000, name: "Havel's Greatshield", type: "weapon", amount: 0, locations: ['anorLondo']},
  {id: 1507000, name: "Greatshield of Artorias", type: "weapon", amount: 0, locations: ['special']},
  {id: 9014000, name: "Cleansing Greatshield", type: "weapon", amount: 0, locations: ['chasmOfTheAbyss']},
  {id: 2006000, name: "Wooden Arrow", type: "ammunition", amount: 0, locations: ['undeadParish','undeadBurg']},
  {id: 2000000, name: "Standard Arrow", type: "ammunition", amount: 0, locations: ['undeadParish','undeadBurg','senFortress','firelinkShrine','anorLondo','theCatacombs']},
  {id: 2001000, name: "Large Arrow", type: "ammunition", amount: 0, locations: ['undeadParish','undeadBurg','senFortress','firelinkShrine','anorLondo','theCatacombs','royalWood','newLondoRuins']},
  {id: 2002000, name: "Feather Arrow", type: "ammunition", amount: 0, locations: ['darkrootBasin','senFortress','anorLondo','royalWood']},
  {id: 2003000, name: "Fire Arrow", type: "ammunition", amount: 0, locations: ['undeadBurg']},
  {id: 2004000, name: "Poison Arrow", type: "ammunition", amount: 0, locations: ['undeadBurg']},
  {id: 2005000, name: "Moonlight Arrow", type: "ammunition", amount: 0, locations: ['anorLondo']},
  {id: 2007000, name: "Dragonslayer Arrow", type: "ammunition", amount: 0, locations: ['anorLondo']},
  {id: 2008000, name: "Gough's Great Arrow", type: "ammunition", amount: 0, locations: ['royalWood','oolacileTownship']},
  {id: 2103000, name: "Wood Bolt", type: "ammunition", amount: 0, locations: ['undeadParish','undeadBurg','anorLondo','firelinkShrine','theCatacombs']},
  {id: 2100000, name: "Standard Bolt", type: "ammunition", amount: 0, locations: ['undeadBurg','undeadParish','anorLondo','firelinkShrine','theCatacombs']},
  {id: 2101000, name: "Heavy Bolt", type: "ammunition", amount: 0, locations: ['undeadParish','senFortress','firelinkShrine','anorLondo','undeadBurg','theCatacombs']},
  {id: 2102000, name: "Sniper Bolt", type: "ammunition", amount: 0, locations: ['senFortress','anorLondo','royalWood']},
  {id: 2104000, name: "Lightning Bolt", type: "ammunition", amount: 0, locations: ['anorLondo']},
  {id: 210000, name: "Standard Helm", type: "armor", amount: 0, locations: ['depths','special']},
  {id: 211000, name: "Hard Leather Armor", type: "armor", amount: 0, locations: ['depths','special']},
  {id: 212000, name: "Hard Leather Gauntlets", type: "armor", amount: 0, locations: ['depths','special']},
  {id: 213000, name: "Hard Leather Boots", type: "armor", amount: 0, locations: ['depths','special']},
  {id: 170000, name: "Chain Helm", type: "armor", amount: 0, locations: ['undeadBurg','oolacileTownship']},
  {id: 171000, name: "Chain Armor", type: "armor", amount: 0, locations: ['undeadBurg','oolacileTownship']},
  {id: 172000, name: "Leather Gauntlets", type: "armor", amount: 0, locations: ['undeadBurg','oolacileTownship']},
  {id: 173000, name: "Chain Leggings", type: "armor", amount: 0, locations: ['undeadBurg','oolacileTownship']},
  {id: 390000, name: "Knight Helm", type: "armor", amount: 0, locations: ['darkrootBasin','special']},
  {id: 391000, name: "Knight Armor", type: "armor", amount: 0, locations: ['darkrootBasin','special']},
  {id: 392000, name: "Knight Gauntlets", type: "armor", amount: 0, locations: ['darkrootBasin','special']},
  {id: 393000, name: "Knight Leggings", type: "armor", amount: 0, locations: ['darkrootBasin','special']},
  {id: 350000, name: "Elite Knight Helm", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 351000, name: "Elite Knight Armor", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 352000, name: "Elite Knight Gauntlets", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 353000, name: "Elite Knight Leggings", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 360000, name: "Wanderer Hood", type: "armor", amount: 0, locations: ['blighttown','special']},
  {id: 361000, name: "Wanderer Coat", type: "armor", amount: 0, locations: ['blighttown','special']},
  {id: 362000, name: "Wanderer Manchette", type: "armor", amount: 0, locations: ['blighttown','special']},
  {id: 363000, name: "Wanderer Boots", type: "armor", amount: 0, locations: ['blighttown','special']},
  {id: 300000, name: "Thief Mask", type: "armor", amount: 0, locations: ['undeadBurg','special']},
  {id: 301000, name: "Black Leather Armor", type: "armor", amount: 0, locations: ['undeadBurg','special']},
  {id: 302000, name: "Black Leather Gloves", type: "armor", amount: 0, locations: ['undeadBurg','special']},
  {id: 303000, name: "Black Leather Boots", type: "armor", amount: 0, locations: ['undeadBurg','special']},
  {id: 50000, name: "Brigand Hood", type: "armor", amount: 0, locations: ['valleyOfDrakes','special']},
  {id: 51000, name: "Brigand Armor", type: "armor", amount: 0, locations: ['valleyOfDrakes','special']},
  {id: 52000, name: "Brigand Gauntlets", type: "armor", amount: 0, locations: ['valleyOfDrakes','special']},
  {id: 53000, name: "Brigand Trousers", type: "armor", amount: 0, locations: ['valleyOfDrakes','special']},
  {id: 241000, name: "Leather Armor", type: "armor", amount: 0, locations: ['darkrootBasin','special']},
  {id: 242000, name: "Leather Gloves", type: "armor", amount: 0, locations: ['darkrootBasin','special']},
  {id: 243000, name: "Leather Boots", type: "armor", amount: 0, locations: ['darkrootBasin','special']},
  {id: 220000, name: "Sorcerer Hat", type: "armor", amount: 0, locations: ['undeadBurg','special']},
  {id: 221000, name: "Sorcerer Cloak", type: "armor", amount: 0, locations: ['undeadBurg','special']},
  {id: 222000, name: "Sorcerer Gauntlets", type: "armor", amount: 0, locations: ['undeadBurg','special']},
  {id: 223000, name: "Sorcerer Boots", type: "armor", amount: 0, locations: ['undeadBurg','special']},
  {id: 640000, name: "Black Sorcerer Hat", type: "armor", amount: 0, locations: ['senFortress']},
  {id: 641000, name: "Black Sorcerer Cloak", type: "armor", amount: 0, locations: ['senFortress']},
  {id: 642000, name: "Black Sorcerer Gauntlets", type: "armor", amount: 0, locations: ['senFortress']},
  {id: 643000, name: "Black Sorcerer Boots", type: "armor", amount: 0, locations: ['senFortress']},
  //  {id: 370000, name: "Mage Smith Hat", type: "armor", amount: 0, locations: []},
  //  {id: 371000, name: "Mage Smith Coat", type: "armor", amount: 0, locations: []},
  //  {id: 372000, name: "Mage Smith Gauntlets", type: "armor", amount: 0, locations: []},
  //  {id: 373000, name: "Mage Smith Boots", type: "armor", amount: 0, locations: []},
  {id: 230000, name: "Tattered Cloth Hood", type: "armor", amount: 0, locations: ['blighttown','special']},
  {id: 231000, name: "Tattered Cloth Robe", type: "armor", amount: 0, locations: ['blighttown','special']},
  {id: 232000, name: "Tattered Cloth Manchette", type: "armor", amount: 0, locations: ['blighttown','special']},
  {id: 233000, name: "Heavy Boots", type: "armor", amount: 0, locations: ['blighttown','special']},
  {id: 310000, name: "Priest's Hat", type: "armor", amount: 0, locations: ['theCatacombs']},
  {id: 311000, name: "Holy Robe", type: "armor", amount: 0, locations: ['theCatacombs','special']},
  {id: 312000, name: "Traveling Gloves", type: "armor", amount: 0, locations: ['theCatacombs','special']},
  {id: 313000, name: "Holy Trousers", type: "armor", amount: 0, locations: ['theCatacombs','special']},
  {id: 180000, name: "Cleric Helm", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 181000, name: "Cleric Armor", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 182000, name: "Cleric Gauntlets", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 183000, name: "Cleric Leggings", type: "armor", amount: 0, locations: ['firelinkShrine']},
  //  {id: 650000, name: "Elite Cleric Helm", type: "armor", amount: 0, locations: []},
  //  {id: 651000, name: "Elite Cleric Armor", type: "armor", amount: 0, locations: []},
  //  {id: 652000, name: "Elite Cleric Gauntlets", type: "armor", amount: 0, locations: []},
  //  {id: 653000, name: "Elite Cleric Leggings", type: "armor", amount: 0, locations: []},
  {id: 160000, name: "Iron Helm", type: "armor", amount: 0, locations: ['undeadParish','anorLondo','lostIzalith']},
  {id: 161000, name: "Armor of the Sun", type: "armor", amount: 0, locations: ['undeadParish','anorLondo','lostIzalith']},
  {id: 162000, name: "Iron Bracelet", type: "armor", amount: 0, locations: ['undeadParish','anorLondo','lostIzalith']},
  {id: 163000, name: "Iron Leggings", type: "armor", amount: 0, locations: ['undeadParish','anorLondo','lostIzalith']},
  {id: 70000, name: "Black Iron Helm", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 71000, name: "Black Iron Armor", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 72000, name: "Black Iron Gauntlets", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 73000, name: "Black Iron Leggings", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 110000, name: "Helm of the Wise", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 111000, name: "Armor of the Glorious", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 112000, name: "Gauntlets of the Vanquisher", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 113000, name: "Boots of the Explorer", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 10000, name: "Catarina Helm", type: "armor", amount: 0, locations: ['senFortress']},
  {id: 11000, name: "Catarina Armor", type: "armor", amount: 0, locations: ['senFortress']},
  {id: 12000, name: "Catarina Gauntlets", type: "armor", amount: 0, locations: ['senFortress']},
  {id: 13000, name: "Catarina Leggings", type: "armor", amount: 0, locations: ['senFortress']},
  {id: 130000, name: "Crystalline Helm", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 131000, name: "Crystalline Armor", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 132000, name: "Crystalline Gauntlets", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 133000, name: "Crystalline Leggings", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 450000, name: "Brass Helm", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 451000, name: "Brass Armor", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 452000, name: "Brass Gauntlets", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 453000, name: "Brass Leggings", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 240000, name: "Pharis's Hat", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 380000, name: "Big Hat", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 381000, name: "Sage Robe", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 382000, name: "Traveling Gloves", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 383000, name: "Traveling Boots", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 140000, name: "Mask of the Sealer", type: "armor", amount: 0, locations: ['blighttown']},
  {id: 141000, name: "Crimson Robe", type: "armor", amount: 0, locations: ['blighttown']},
  {id: 142000, name: "Crimson Gloves", type: "armor", amount: 0, locations: ['blighttown']},
  {id: 143000, name: "Crimson Waistcloth", type: "armor", amount: 0, locations: ['blighttown']},
  {id: 340000, name: "Witch Hat", type: "armor", amount: 0, locations: ['valleyOfDrakes']},
  {id: 341000, name: "Witch Cloak", type: "armor", amount: 0, locations: ['valleyOfDrakes']},
  {id: 342000, name: "Witch Gloves", type: "armor", amount: 0, locations: ['valleyOfDrakes']},
  {id: 343000, name: "Witch Skirt", type: "armor", amount: 0, locations: ['valleyOfDrakes']},
  {id: 330000, name: "Crown of Dusk", type: "armor", amount: 0, locations: ['darkrootBasin']},
  {id: 331000, name: "Antiquated Dress", type: "armor", amount: 0, locations: ['darkrootBasin']},
  {id: 332000, name: "Antiquated Gloves", type: "armor", amount: 0, locations: ['darkrootBasin']},
  {id: 333000, name: "Antiquated Skirt", type: "armor", amount: 0, locations: ['darkrootBasin']},
  {id: 460000, name: "Gold-Hemmed Black Hood", type: "armor", amount: 0, locations: ['demonsRuins']},
  {id: 461000, name: "Gold-Hemmed Black Cloak", type: "armor", amount: 0, locations: ['demonsRuins']},
  {id: 462000, name: "Gold-Hemmed Black Gloves", type: "armor", amount: 0, locations: ['demonsRuins']},
  {id: 463000, name: "Gold-Hemmed Black Skirt", type: "armor", amount: 0, locations: ['demonsRuins']},
  {id: 150000, name: "Mask of Velka", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 151000, name: "Black Cleric Robe", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 152000, name: "Black Manchette", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 153000, name: "Black Tights", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 700000, name: "Snickering Top Hat", type: "armor", amount: 0, locations: ['royalWood']},
  {id: 701000, name: "Chester's Long Coat", type: "armor", amount: 0, locations: ['royalWood']},
  {id: 702000, name: "Chester's Gloves", type: "armor", amount: 0, locations: ['royalWood']},
  {id: 703000, name: "Chester's Trousers", type: "armor", amount: 0, locations: ['royalWood']},
  {id: 410000, name: "Maiden Hood", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 411000, name: "Maiden Robe", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 412000, name: "Maiden Gloves", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 413000, name: "Maiden Skirt", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 400000, name: "Dingy Hood", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 401000, name: "Dingy Robe", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 402000, name: "Dingy Gloves", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 403000, name: "Blood-Stained Skirt", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 280000, name: "Eastern Helm", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 281000, name: "Eastern Armor", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 282000, name: "Eastern Gauntlets", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 283000, name: "Eastern Leggings", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 60000, name: "Shadow Mask", type: "armor", amount: 0, locations: ['blighttown']},
  {id: 61000, name: "Shadow Garb", type: "armor", amount: 0, locations: ['blighttown']},
  {id: 62000, name: "Shadow Gauntlets", type: "armor", amount: 0, locations: ['blighttown']},
  {id: 63000, name: "Shadow Leggings", type: "armor", amount: 0, locations: ['blighttown']},
  {id: 520000, name: "Hollow Warrior Helm", type: "armor", amount: 0, locations: ['undeadBurg']},
  {id: 521000, name: "Hollow Warrior Armor", type: "armor", amount: 0, locations: ['undeadBurg']},
  {id: 523000, name: "Hollow Warrior Waistcloth", type: "armor", amount: 0, locations: ['undeadBurg']},
  {id: 480000, name: "Hollow Soldier Helm", type: "armor", amount: 0, locations: ['undeadAsylum','undeadBurg','undeadParish']},
  {id: 481000, name: "Hollow Soldier Armor", type: "armor", amount: 0, locations: ['undeadAsylum','undeadBurg','undeadParish']},
  {id: 483000, name: "Hollow Soldier Waistcloth", type: "armor", amount: 0, locations: ['undeadAsylum','undeadBurg','undeadParish']},
  {id: 510000, name: "Balder Helm", type: "armor", amount: 0, locations: ['undeadParish','senFortress']},
  {id: 511000, name: "Balder Armor", type: "armor", amount: 0, locations: ['undeadParish','senFortress']},
  {id: 512000, name: "Balder Gauntlets", type: "armor", amount: 0, locations: ['undeadParish','senFortress']},
  {id: 513000, name: "Balder Leggings", type: "armor", amount: 0, locations: ['undeadParish','senFortress']},
  {id: 490000, name: "Steel Helm", type: "armor", amount: 0, locations: ['undeadParish','senFortress','paintedWorldOfAriamis']},
  {id: 491000, name: "Steel Armor", type: "armor", amount: 0, locations: ['undeadParish','senFortress','paintedWorldOfAriamis']},
  {id: 492000, name: "Steel Gauntlets", type: "armor", amount: 0, locations: ['undeadParish','senFortress','paintedWorldOfAriamis']},
  {id: 493000, name: "Steel Leggings", type: "armor", amount: 0, locations: ['undeadParish','senFortress','paintedWorldOfAriamis']},
  {id: 500000, name: "Hollow Thief's Hood", type: "armor", amount: 0, locations: ['undeadBurg']},
  {id: 501000, name: "Hollow Thief's Leather Armor", type: "armor", amount: 0, locations: ['undeadBurg']},
  {id: 503000, name: "Hollow Thief's Tights", type: "armor", amount: 0, locations: ['undeadBurg']},
  {id: 420000, name: "Silver Knight Helm", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 421000, name: "Silver Knight Armor", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 422000, name: "Silver Knight Gauntlets", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 423000, name: "Silver Knight Leggings", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 320000, name: "Black Knight Helm", type: "armor", amount: 0, locations: ['kilnOfTheFirstFlame']},
  {id: 321000, name: "Black Knight Armor", type: "armor", amount: 0, locations: ['kilnOfTheFirstFlame']},
  {id: 322000, name: "Black Knight Gauntlets", type: "armor", amount: 0, locations: ['kilnOfTheFirstFlame']},
  {id: 323000, name: "Black Knight Leggings", type: "armor", amount: 0, locations: ['kilnOfTheFirstFlame']},
  {id: 530000, name: "Giant Helm", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 531000, name: "Giant Armor", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 532000, name: "Giant Gauntlets", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 533000, name: "Giant Leggings", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 90000, name: "Six-Eyed Helm of the Channelers", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 91000, name: "Robe of the Channelers", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 92000, name: "Gauntlets of the Channelers", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 93000, name: "Waistcloth of the Channelers", type: "armor", amount: 0, locations: ['theDukeArchives']},
  {id: 250000, name: "Painting Guardian Hood", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 251000, name: "Painting Guardian Robe", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 252000, name: "Painting Guardian Gloves", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 253000, name: "Painting Guardian Waistcloth", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 620000, name: "Fang Boar Helm", type: "armor", amount: 0, locations: ['undeadParish','theDukeArchives']},
  {id: 630000, name: "Gargoyle Helm", type: "armor", amount: 0, locations: ['undeadParish','anorLondo']},
  {id: 470000, name: "Golem Helm", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 471000, name: "Golem Armor", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 472000, name: "Golem Gauntlets", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 473000, name: "Golem Leggings", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 80000, name: "Smough's Helm", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 81000, name: "Smough's Armor", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 82000, name: "Smough's Gauntlets", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 83000, name: "Smough's Leggings", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 270000, name: "Ornstein's Helm", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 271000, name: "Ornstein's Armor", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 272000, name: "Ornstein's Gauntlets", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 273000, name: "Ornstein's Leggings", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 660000, name: "Helm of Artorias", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 661000, name: "Armor of Artorias", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 662000, name: "Gauntlets of Artorias", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 663000, name: "Leggings of Artorias", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 680000, name: "Gough's Helm", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 681000, name: "Gough's Armor", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 682000, name: "Gough's Gauntlets", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 683000, name: "Gough's Leggings", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 670000, name: "Porcelain Mask", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 671000, name: "Lord's Blade Robe", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 672000, name: "Lord's Blade Gloves", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 673000, name: "Lord's Blade Waistcloth", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 540000, name: "Crown of the Dark Sun", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 541000, name: "Moonlight Robe", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 542000, name: "Moonlight Gloves", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 543000, name: "Moonlight Waistcloth", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 550000, name: "Crown of the Great Lord", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 551000, name: "Robe of the Great Lord", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 552000, name: "Bracelet of the Great Lord", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 553000, name: "Anklet of the Great Lord", type: "armor", amount: 0, locations: ['firelinkShrine']},
  {id: 40000, name: "Dark Mask", type: "armor", amount: 0, locations: ['theAbyss']},
  {id: 41000, name: "Dark Armor", type: "armor", amount: 0, locations: ['theAbyss']},
  {id: 42000, name: "Dark Gauntlets", type: "armor", amount: 0, locations: ['theAbyss']},
  {id: 43000, name: "Dark Leggings", type: "armor", amount: 0, locations: ['theAbyss']},
  {id: 200000, name: "Helm of Thorns", type: "armor", amount: 0, locations: ['quelaagDomain']},
  {id: 201000, name: "Armor of Thorns", type: "armor", amount: 0, locations: ['quelaagDomain']},
  {id: 202000, name: "Gauntlets of Thorns", type: "armor", amount: 0, locations: ['quelaagDomain']},
  {id: 203000, name: "Leggings of Thorns", type: "armor", amount: 0, locations: ['quelaagDomain']},
  {id: 100000, name: "Helm of Favor", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 101000, name: "Embraced Armor of Favor", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 102000, name: "Gauntlets of Favor", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 103000, name: "Leggings of Favor", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 20000, name: "Paladin Helm", type: "armor", amount: 0, locations: ['tombOfTheGiants']},
  {id: 21000, name: "Paladin Armor", type: "armor", amount: 0, locations: ['tombOfTheGiants']},
  {id: 22000, name: "Paladin Gauntlets", type: "armor", amount: 0, locations: ['tombOfTheGiants']},
  {id: 23000, name: "Paladin Leggings", type: "armor", amount: 0, locations: ['tombOfTheGiants']},
  {id: 120000, name: "Stone Helm", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 121000, name: "Stone Armor", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 122000, name: "Stone Gauntlets", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 123000, name: "Stone Leggings", type: "armor", amount: 0, locations: ['darkrootGarden']},
  {id: 690000, name: "Guardian Helm", type: "armor", amount: 0, locations: ['royalWood']},
  {id: 691000, name: "Guardian Armor", type: "armor", amount: 0, locations: ['royalWood']},
  {id: 692000, name: "Guardian Gauntlets", type: "armor", amount: 0, locations: ['royalWood']},
  {id: 693000, name: "Guardian Leggings", type: "armor", amount: 0, locations: ['royalWood']},
  {id: 440000, name: "Havel's Helm", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 441000, name: "Havel's Armor", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 442000, name: "Havel's Gauntlets", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 443000, name: "Havel's Leggings", type: "armor", amount: 0, locations: ['anorLondo']},
  {id: 290000, name: "Xanthous Crown", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 291000, name: "Xanthous Overcoat", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 292000, name: "Xanthous Gloves", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 293000, name: "Xanthous Waistcloth", type: "armor", amount: 0, locations: ['paintedWorldOfAriamis']},
  {id: 590000, name: "Mask of the Father", type: "armor", amount: 0, locations: ['firelinkShrine','theCatacombs','tombOfTheGiants']},
  {id: 600000, name: "Mask of the Mother", type: "armor", amount: 0, locations: ['firelinkShrine','theCatacombs','tombOfTheGiants']},
  {id: 610000, name: "Mask of the Child", type: "armor", amount: 0, locations: ['firelinkShrine','theCatacombs','tombOfTheGiants']},
  {id: 580000, name: "Royal Helm", type: "armor", amount: 0, locations: ['theCatacombs']},
  {id: 560000, name: "Sack", type: "armor", amount: 0, locations: ['theCatacombs']},
  {id: 190000, name: "Sunlight Maggot", type: "armor", amount: 0, locations: ['demonsRuins']},
  {id: 570000, name: "Symbol of Avarice", type: "armor", amount: 0, locations: ['senFortress','anorLondo','theDukeArchives']},
  {id: 710000, name: "Bloated Head", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 720000, name: "Bloated Sorcerer Head", type: "armor", amount: 0, locations: ['oolacileTownship']},
  {id: 111, name: "Tiny Being's Ring", type: "ring", amount: 0, locations: ['anorLondo','special']},
  {id: 104, name: "Cloranthy Ring", type: "ring", amount: 0, locations: ['theGreatHollow']},
  {id: 100, name: "Havel's Ring", type: "ring", amount: 0, locations: ['darkrootBasin']},
  {id: 120, name: "Ring of Steel Protection", type: "ring", amount: 0, locations: ['senFortress']},
  {id: 107, name: "Spell Stoneplate Ring", type: "ring", amount: 0, locations: ['senFortress']},
  {id: 105, name: "Flame Stoneplate Ring", type: "ring", amount: 0, locations: ['senFortress']},
  {id: 106, name: "Thunder Stoneplate Ring", type: "ring", amount: 0, locations: ['senFortress']},
  {id: 108, name: "Speckled Stoneplate Ring", type: "ring", amount: 0, locations: ['senFortress','lostIzalith']},
  {id: 109, name: "Bloodbite Ring", type: "ring", amount: 0, locations: ['undeadParish']},
  {id: 110, name: "Poisonbite Ring", type: "ring", amount: 0, locations: ['undeadParish']},
  {id: 113, name: "Cursebite Ring", type: "ring", amount: 0, locations: ['newLondoRuins']},
  {id: 101, name: "Red Tearstone Ring", type: "ring", amount: 0, locations: ['valleyOfDrakes']},
  {id: 147, name: "Blue Tearstone Ring", type: "ring", amount: 0, locations: ['undeadBurg']},
  {id: 126, name: "Ring of Sacrifice", type: "ring", amount: 0, locations: ['firelinkShrine','undeadParish','undeadAsylum']},
  {id: 127, name: "Rare Ring of Sacrifice", type: "ring", amount: 0, locations: ['senFortress','newLondoRuins','undeadAsylum']},
  {id: 115, name: "Bellowing Dragoncrest Ring", type: "ring", amount: 0, locations: ['firelinkShrine']},
  {id: 141, name: "Lingering Dragoncrest Ring", type: "ring", amount: 0, locations: ['firelinkShrine']},
  {id: 123, name: "Slumbering Dragoncrest Ring", type: "ring", amount: 0, locations: ['firelinkShrine','senFortress']},
  {id: 116, name: "Dusk Crown Ring", type: "ring", amount: 0, locations: ['darkrootBasin']},
  {id: 114, name: "White Seance Ring", type: "ring", amount: 0, locations: ['theDukeArchives']},
  {id: 149, name: "Darkmoon Seance Ring", type: "ring", amount: 0, locations: ['theCatacombs']},
  {id: 148, name: "Ring of the Sun's Firstborn", type: "ring", amount: 0, locations: ['anorLondo']},
  {id: 102, name: "Darkmoon Blade Covenant Ring", type: "ring", amount: 0, locations: ['anorLondo']},
  {id: 130, name: "Ring of the Sun Princess", type: "ring", amount: 0, locations: ['anorLondo']},
  {id: 144, name: "Leo Ring", type: "ring", amount: 0, locations: ['anorLondo']},
  {id: 146, name: "Wolf Ring", type: "ring", amount: 0, locations: ['darkrootGarden']},
  {id: 119, name: "Hawk Ring", type: "ring", amount: 0, locations: ['anorLondo']},
  {id: 117, name: "Hornet Ring", type: "ring", amount: 0, locations: ['darkrootGarden']},
  {id: 145, name: "East Wood Grain Ring", type: "ring", amount: 0, locations: ['blighttown']},
  {id: 128, name: "Dark Wood Grain Ring", type: "ring", amount: 0, locations: ['darkrootGarden','blighttown']},
  {id: 125, name: "Rusted Iron Ring", type: "ring", amount: 0, locations: ['undeadAsylum']},
  {id: 121, name: "Covetous Gold Serpent Ring", type: "ring", amount: 0, locations: ['senFortress']},
  {id: 122, name: "Covetous Silver Serpent Ring", type: "ring", amount: 0, locations: ['tombOfTheGiants']},
  {id: 138, name: "Covenant of Artorias", type: "ring", amount: 0, locations: ['darkrootGarden']},
  {id: 139, name: "Orange Charred Ring", type: "ring", amount: 0, locations: ['lostIzalith']},
  {id: 137, name: "Old Witch's Ring", type: "ring", amount: 0, locations: ['undeadAsylum','special']},
  {id: 103, name: "Cat Covenant Ring", type: "ring", amount: 0, locations: ['darkrootGarden']},
  {id: 124, name: "Ring of Fog", type: "ring", amount: 0, locations: ['darkrootGarden','undeadAsylum']},
  {id: 143, name: "Ring of Favor and Protection", type: "ring", amount: 0, locations: ['firelinkShrine','undeadBurg','anorLondo','undeadAsylum']},
  {id: 142, name: "Ring of the Evil Eye", type: "ring", amount: 0, locations: ['depths']},
  {id: 150, name: "Calamity Ring", type: "ring", amount: 0, locations: ['royalWood']}
];
